### ISSUE TITLE
Repository is too heavy for cloning

### ISSUE THREAD

**Issue by Matipedia** [dccuchile/CC6205#1]
Git clone takes way too long :-1: 

I suggest to split this repository into at least two: class material (PDF, tex files, etc) and utilities like sample code, data samples or examples.
Git sub-modules can be used to achieve the same.

Another suggestion is to keep only the TEX files on git and upload PDF's to U-cursos.

**Comment by felipebravom** [comment]
Heavy files are now being stored as binary files in a repo release.
