### ISSUE TITLE
Tagging and Hidden Markov Models (slides by Michael Collins)

### ISSUE THREAD

**Issue by ansegura7** [dccuchile/CC6205#8]
Hi. The links to the presentations and notes in section 8 (_Tagging and Hidden Markov Models_) in the README are not working. Can you please update them?

**Comment by felipebravom** [comment]
Hi,
I just tried the link and it worked fine:
http://www.cs.columbia.edu/~mcollins/cs4705-spring2019/slides/tagging.pdf
Cheers,
Felipe

**Comment by ansegura7** [comment]
Hi. Yes, you are absolutely right. It seems to be some weird configuration of my browser.
Please forget my comment and regards.
